# Generated by Django 4.0.4 on 2022-04-23 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phoneNumbers',
        ),
        migrations.AddField(
            model_name='email',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_emails', to='userservice.user'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_phone_numbers', to='userservice.user'),
        ),
    ]
